version: "2"

services:
  stripe-mock:
    image: stripemock/stripe-mock:latest
    ports:
      - "12111-12112:12111-12112"
  rabbit:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
