// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: claim.proto

package payment

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Claim struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID     string                `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Payee  string                `protobuf:"bytes,2,opt,name=Payee,proto3" json:"Payee,omitempty"`
	Amount *Claim_MonetaryAmount `protobuf:"bytes,3,opt,name=Amount,proto3" json:"Amount,omitempty"`
	Payer  *Claim_Card           `protobuf:"bytes,4,opt,name=Payer,proto3" json:"Payer,omitempty"`
}

func (x *Claim) Reset() {
	*x = Claim{}
	if protoimpl.UnsafeEnabled {
		mi := &file_claim_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Claim) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim) ProtoMessage() {}

func (x *Claim) ProtoReflect() protoreflect.Message {
	mi := &file_claim_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim.ProtoReflect.Descriptor instead.
func (*Claim) Descriptor() ([]byte, []int) {
	return file_claim_proto_rawDescGZIP(), []int{0}
}

func (x *Claim) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Claim) GetPayee() string {
	if x != nil {
		return x.Payee
	}
	return ""
}

func (x *Claim) GetAmount() *Claim_MonetaryAmount {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *Claim) GetPayer() *Claim_Card {
	if x != nil {
		return x.Payer
	}
	return nil
}

type Claim_MonetaryAmount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Currency string `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Value    int64  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Claim_MonetaryAmount) Reset() {
	*x = Claim_MonetaryAmount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_claim_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Claim_MonetaryAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim_MonetaryAmount) ProtoMessage() {}

func (x *Claim_MonetaryAmount) ProtoReflect() protoreflect.Message {
	mi := &file_claim_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim_MonetaryAmount.ProtoReflect.Descriptor instead.
func (*Claim_MonetaryAmount) Descriptor() ([]byte, []int) {
	return file_claim_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Claim_MonetaryAmount) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Claim_MonetaryAmount) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

type Claim_ExpirationDate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Year  string `protobuf:"bytes,1,opt,name=year,proto3" json:"year,omitempty"`
	Month string `protobuf:"bytes,2,opt,name=month,proto3" json:"month,omitempty"`
}

func (x *Claim_ExpirationDate) Reset() {
	*x = Claim_ExpirationDate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_claim_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Claim_ExpirationDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim_ExpirationDate) ProtoMessage() {}

func (x *Claim_ExpirationDate) ProtoReflect() protoreflect.Message {
	mi := &file_claim_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim_ExpirationDate.ProtoReflect.Descriptor instead.
func (*Claim_ExpirationDate) Descriptor() ([]byte, []int) {
	return file_claim_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Claim_ExpirationDate) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *Claim_ExpirationDate) GetMonth() string {
	if x != nil {
		return x.Month
	}
	return ""
}

type Claim_Card struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number    string                `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	ExpiresAt *Claim_ExpirationDate `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (x *Claim_Card) Reset() {
	*x = Claim_Card{}
	if protoimpl.UnsafeEnabled {
		mi := &file_claim_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Claim_Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Claim_Card) ProtoMessage() {}

func (x *Claim_Card) ProtoReflect() protoreflect.Message {
	mi := &file_claim_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Claim_Card.ProtoReflect.Descriptor instead.
func (*Claim_Card) Descriptor() ([]byte, []int) {
	return file_claim_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Claim_Card) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *Claim_Card) GetExpiresAt() *Claim_ExpirationDate {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_claim_proto protoreflect.FileDescriptor

var file_claim_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x63, 0x6c, 0x61, 0x69, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xed, 0x02, 0x0a, 0x05, 0x43, 0x6c, 0x61, 0x69, 0x6d,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44,
	0x12, 0x14, 0x0a, 0x05, 0x50, 0x61, 0x79, 0x65, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x50, 0x61, 0x79, 0x65, 0x65, 0x12, 0x35, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74,
	0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x2e, 0x4d, 0x6f, 0x6e, 0x65, 0x74, 0x61, 0x72, 0x79, 0x41,
	0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x29, 0x0a,
	0x05, 0x50, 0x61, 0x79, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x2e, 0x43, 0x61, 0x72,
	0x64, 0x52, 0x05, 0x50, 0x61, 0x79, 0x65, 0x72, 0x1a, 0x42, 0x0a, 0x0e, 0x4d, 0x6f, 0x6e, 0x65,
	0x74, 0x61, 0x72, 0x79, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75,
	0x72, 0x72, 0x65, 0x6e, 0x63, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x1a, 0x3a, 0x0a, 0x0e,
	0x45, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x79, 0x65, 0x61, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x79, 0x65,
	0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x1a, 0x5c, 0x0a, 0x04, 0x43, 0x61, 0x72, 0x64,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x3c, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69,
	0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x6c, 0x61, 0x69, 0x6d, 0x2e, 0x45, 0x78, 0x70,
	0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x52, 0x09, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x61, 0x6e, 0x6e, 0x69, 0x6f, 0x6e, 0x30, 0x30, 0x37, 0x2f,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x79,
	0x70, 0x65, 0x2f, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x3b, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_claim_proto_rawDescOnce sync.Once
	file_claim_proto_rawDescData = file_claim_proto_rawDesc
)

func file_claim_proto_rawDescGZIP() []byte {
	file_claim_proto_rawDescOnce.Do(func() {
		file_claim_proto_rawDescData = protoimpl.X.CompressGZIP(file_claim_proto_rawDescData)
	})
	return file_claim_proto_rawDescData
}

var file_claim_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_claim_proto_goTypes = []interface{}{
	(*Claim)(nil),                // 0: payment.Claim
	(*Claim_MonetaryAmount)(nil), // 1: payment.Claim.MonetaryAmount
	(*Claim_ExpirationDate)(nil), // 2: payment.Claim.ExpirationDate
	(*Claim_Card)(nil),           // 3: payment.Claim.Card
}
var file_claim_proto_depIdxs = []int32{
	1, // 0: payment.Claim.Amount:type_name -> payment.Claim.MonetaryAmount
	3, // 1: payment.Claim.Payer:type_name -> payment.Claim.Card
	2, // 2: payment.Claim.Card.expires_at:type_name -> payment.Claim.ExpirationDate
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_claim_proto_init() }
func file_claim_proto_init() {
	if File_claim_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_claim_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Claim); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_claim_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Claim_MonetaryAmount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_claim_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Claim_ExpirationDate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_claim_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Claim_Card); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_claim_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_claim_proto_goTypes,
		DependencyIndexes: file_claim_proto_depIdxs,
		MessageInfos:      file_claim_proto_msgTypes,
	}.Build()
	File_claim_proto = out.File
	file_claim_proto_rawDesc = nil
	file_claim_proto_goTypes = nil
	file_claim_proto_depIdxs = nil
}
